apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: dmp-poc
  labels:
    app: mcp-server
spec:
  type: ClusterIP
  selector:
    app: mcp-server
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP

